custom_gamma_pursuer: True
gamma_p: 0.7

custom_gamma_evader: True
gamma_e: 0.7


numActionsVec: [4]
numRoundsVec: [100000]
numPlays_LBVec: [2]
numPlays_UBVec: [2]

rewardMax: 1.0
rewardMin: 0.0

results_dir: '../results/MABVP_05_14'
summaries_dir: '../results/summaries/MABVP_05_14/'
plots_dir: '../results/plots/MABVP_05_14/'
